apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler-fetcher
  labels:
    app: crawler-fetcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler-fetcher
  template:
    metadata:
      labels:
        app: crawler-fetcher
    spec:
      containers:
      - name: fetcher
        image: web-crawler:local
        imagePullPolicy: IfNotPresent
        command: ["bun", "run", "start"]
        env:
          - name: DISABLE_DASHBOARD
            value: "true"
        envFrom:
        - configMapRef:
            name: crawler-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
