apiVersion: v1
kind: Secret
metadata:
  name: crawler-secrets
type: Opaque
stringData:
  REDIS_URL: "redis://username:password@doks-redis-cluster:6379"
  MONGO_URL: "mongodb+srv://username:password@doks-mongo-cluster/crawler?retryWrites=true&w=majority"
  S3_ENDPOINT: "https://nyc3.digitaloceanspaces.com"
  S3_ACCESS_KEY_ID: "YOUR_ACCESS_KEY"
  S3_SECRET_ACCESS_KEY: "YOUR_SECRET_KEY"
